# Generated by Django 6.0.6 on 2026-06-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('white_win', 'White Wins (1-0)'), ('black_win', 'Black Wins (0-1)'), ('draw', 'Draw (½-½)'), ('white_forfeit', 'White Forfeits'), ('black_forfeit', 'Black Forfeits'), ('pending', 'Not Yet Played')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('board_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pgn', models.TextField(blank=True, help_text='Game in PGN notation for analysis')),
                ('lichess_game_id', models.CharField(blank=True, max_length=100)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_black', to='members.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_white', to='members.member')),
            ],
            options={
                'ordering': ['round__number', 'board_number'],
            },
        ),
    ]
