# Generated by Django 6.0.6 on 2026-07-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_black_player'),
        ('members', '0002_ratinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('challenger_win', 'Challenger Wins'), ('opponent_win', 'Opponent Wins'), ('draw', 'Draw')], max_length=20)),
                ('lichess_game_id', models.CharField(blank=True, max_length=100)),
                ('elo_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to='members.member')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
