# Generated by Django 6.0.6 on 2026-07-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paynow_reference',
            field=models.CharField(blank=True, help_text='Paynow internal reference', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Mobile money phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='poll_url',
            field=models.URLField(blank=True, help_text='Paynow poll URL for status checks', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting Phone Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
