# Generated by Django 6.0.6 on 2026-07-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_black_player'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('delta', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes', to='matches.match')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='members.member')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
