# Generated by Django 6.0.6 on 2026-07-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_ratinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_players', to='members.member'),
        ),
    ]
