# Generated by Django 6.0.6 on 2026-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
